.PHONY: help install up down migrate seed api worker beat test lint fmt \
        db-new db-up db-down db-redo db-current db-history db-heads db-check db-dump

help:
	@grep -E '^[a-zA-Z_-]+:.*?## .*$$' $(MAKEFILE_LIST) | awk 'BEGIN{FS=":.*?## "}{printf "  %-14s %s\n", $$1, $$2}'

install:  ## install package + dev deps
	pip install -e ".[dev]"

up:       ## start infra containers (pg, redis, qdrant, mailhog)
	docker compose up -d postgres redis qdrant mailhog

down:     ## stop all containers
	docker compose down

seed:     ## load demo data (schema must be at head first)
	python scripts/seed_data.py

api:      ## run the API with reload (watches app/ only)
	uvicorn app.main:app --reload --reload-dir app

worker:   ## run a celery worker
	celery -A app.workers.celery_app worker -l info

beat:     ## run celery beat
	celery -A app.workers.celery_app beat -l info

test:     ## run tests
	pytest -q

lint:     ## ruff + mypy
	ruff check app tests && mypy app

fmt:      ## ruff format + import sort
	ruff format app tests && ruff check --fix app tests

# ── database (Alembic) ───────────────────────────────────────────────
migrate: db-up   ## alias for db-up

db-new:   ## new autogenerated migration:  make db-new m="add foo table"
	@test -n "$(m)" || (echo "usage: make db-new m=\"message\"" && exit 1)
	alembic revision --autogenerate -m "$(m)"

db-up:    ## apply all pending migrations
	alembic upgrade head

db-down:  ## roll back the last migration
	alembic downgrade -1

db-redo:  ## roll back then re-apply the last migration (exercises downgrade())
	alembic downgrade -1 && alembic upgrade head

db-current: ## show the revision the DB is on
	alembic current --verbose

db-history: ## show the full migration history
	alembic history --indicate-current

db-heads: ## show head revision(s) — more than one means a branch to merge
	alembic heads --verbose

db-check: ## fail if models changed without a matching migration
	alembic check

db-dump:  ## write current schema to schema.sql (review / ERD artifact)
	pg_dump "$${DATABASE_URL:-postgresql://$${POSTGRES_USER:-grd}:$${POSTGRES_PASSWORD:-grd}@localhost:5432/$${POSTGRES_DB:-grd_stk_mkt}}" \
	  --schema-only --no-owner --no-privileges > schema.sql
	@echo "wrote schema.sql"
